// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEdB21uNa9IY1iDp6WwLEg7t--WVAFI20',
    appId: '1:502636521814:android:a7fcfe462c769748bc4ef7',
    messagingSenderId: '502636521814',
    projectId: 'hinata-bb170',
    storageBucket: 'hinata-bb170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpvkQNDhq84a0Ryh2G-ucOeAy6zKSyUVQ',
    appId: '1:502636521814:ios:30aff68c9b219b3ebc4ef7',
    messagingSenderId: '502636521814',
    projectId: 'hinata-bb170',
    storageBucket: 'hinata-bb170.firebasestorage.app',
    iosBundleId: 'com.ahmadre.hinata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpvkQNDhq84a0Ryh2G-ucOeAy6zKSyUVQ',
    appId: '1:502636521814:ios:30aff68c9b219b3ebc4ef7',
    messagingSenderId: '502636521814',
    projectId: 'hinata-bb170',
    storageBucket: 'hinata-bb170.firebasestorage.app',
    iosBundleId: 'com.ahmadre.hinata',
  );
}
