import 'dart:js_interop';

/// Set by `config.js` (regenerated by the Docker entrypoint from the
/// `HINATA_DEFAULT_SERVER` container env). Undefined/empty ⇒ connect screen.
@JS('hinataDefaultServer')
external JSString? get _hinataDefaultServer;

String readRuntimeDefaultServer() => _hinataDefaultServer?.toDart ?? '';
